name: timed_builder
description: A widget that rebuilds itself on scheduled, periodic, or dynamically generated time events.
author: Peter Bryant <peter@ptrbrynt.com>
homepage: https://github.com/ptrbrynt/flutter-timer-builder
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
